version: "3"
services:
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=prediction_db
  service:
    image: "cricped-backend"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prediction_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
    depends_on:
      - db
