version: "3"
services:
  db:
    image: "mysql:5.7"
    command: --init-file /init.sql
    volumes:
        - ./init.sql:/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: prediction_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: secret
  service:
    image: "cricped-backend"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prediction_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
    depends_on:
      - db
