spring:
  profiles:
    active: dev

game:
    match:
        losePoints: -50
        winPoints: 100
        noPredictPoints: -100
    toss:
        losePoints: -25
        winPoints: 50
        noPredictPoints: -50
    mom:
        winPoints: 200
        losePoints: 0
        noPredictPoints: 0
    bonusPoints: 250
    semisToss:
      winPoints: 100
    semisMatch:
      winPoints: 200
      bonusPoints: 500
    semisMom:
      winPoints: 400
    finalsToss:
      winPoints: 200
    finalsMatch:
      winPoints: 400
      bonusPoints: 1000
    finalsMom:
      winPoints: 800
    players:
      pot: 50
      hwt: 25
      hrg: 25
      bonus: 500

matchMgmt:
    baseUrl: v1/matchMgmt
predictionMgmt:
    baseUrl: v1/predmgmt
resultMgmt:
    baseUrl: v1/resultMgmt
userMgmt:
    baseUrl: v1/usermgmt

server:
    port: 8090

updateResult:
    cron: 0 0 0,12 * * * #Cron expression to run cron job at 12 am and 12 pm everyday

predictionTimeLimit: 1 # 1 hour before the match
